"""HS-38-06 demo — the GitHub write-connector loop end to end, with audit trail.

Drives the full actuator loop on the Phase-38 GitHub write connector with an
**injected runner** (no real `gh`): propose → approve → execute → audit, plus the
load-bearing negatives (execute before approval, and a manifest-refused op ⇒ no
egress). Writes a reproducible transcript to `actuator_write_loop.md`.

Run from the repo root:

    uv run python3 pm/roadmap/holdspeak/phase-38-actuators-ii/evidence/demo_write_loop.py
"""
from __future__ import annotations

import subprocess
import tempfile
from datetime import datetime
from pathlib import Path

from holdspeak.db import Database, reset_database
from holdspeak.meeting_session import MeetingState
from holdspeak.plugins.actuator_executor import ActuatorExecutionError, ActuatorExecutor
from holdspeak.plugins.actuators import ActuatorProposal
from holdspeak.plugins.builtin.github_issue_actuator import (
    GITHUB_ISSUE_MANIFEST,
    GithubIssueActuator,
    build_github_issue_connector,
    register_github_issue_actuator,
)
from holdspeak.plugins.contracts import PluginRun
from holdspeak.plugins.gated_connector import (
    ConnectorOperationRefused,
    GatedOperation,
    build_gated_connector,
)
from holdspeak.plugins.host import PluginHost
from holdspeak.plugins.persistence import record_actuator_proposal

ACTUATOR_ID = GithubIssueActuator.id
OUT = Path(__file__).with_name("actuator_write_loop.md")

CONTEXT = {
    "meeting_title": "Release planning",
    "github_repo": "acme/app",
    "action_items": [
        {"task": "Cut the v0.3 release notes", "owner": "Dana"},
        {"task": "Wire the staging smoke test", "owner": None},  # unowned → proposed
    ],
}


class FakeGh:
    """Stands in for subprocess.run — records argv, returns a canned issue URL."""

    def __init__(self, *, returncode=0, stdout="", stderr=""):
        self.calls: list[list[str]] = []
        self._rc, self._out, self._err = returncode, stdout, stderr

    def __call__(self, argv, **kwargs):
        self.calls.append(list(argv))
        return subprocess.CompletedProcess(argv, self._rc, stdout=self._out, stderr=self._err)


def _propose(db, host) -> str:
    result = host.execute(ACTUATOR_ID, context=dict(CONTEXT), meeting_id="m1", window_id="w1", transcript_hash="h1")
    run = PluginRun(
        plugin_id=result.plugin_id, plugin_version=result.plugin_version, window_id="w1",
        meeting_id="m1", profile="balanced", status="proposed",
        idempotency_key=result.idempotency_key, started_at=0.0, finished_at=0.1,
        duration_ms=result.duration_ms, output=result.output,
    )
    record_actuator_proposal(db, run)
    return db.actuators.list_proposals("m1")[0].id


def main() -> None:
    reset_database()
    tmp = Path(tempfile.mkdtemp())
    db = Database(tmp / "demo.db")
    db.meetings.save_meeting(MeetingState(id="m1", started_at=datetime.now(), title="Release planning", segments=[]))

    host = PluginHost(default_timeout_seconds=1.0, enabled_capabilities={"actuator"})
    register_github_issue_actuator(host)
    gh = FakeGh(stdout="https://github.com/acme/app/issues/128")
    connector = build_github_issue_connector(runner=gh)

    lines: list[str] = []
    w = lines.append
    w("# Demo — GitHub write-connector loop (HS-38-06)\n")
    w("Generated by `demo_write_loop.py` — an injected `gh` runner (no real GitHub call).\n")
    w("The actuator proposes a GitHub issue for the first **unowned** action item; the")
    w("connector runs `gh issue create` (and only that) behind `shell:exec` + the manifest.\n")

    # 1. Propose
    pid = _propose(db, host)
    p = db.actuators.get_proposal(pid)
    w("## 1. Propose (the actuator never acts)\n")
    w(f"- status: **{p.status}**")
    w(f"- preview: {p.preview}")
    w(f"- payload: `{p.payload}`")
    w(f"- `gh` calls so far: **{len(gh.calls)}**\n")

    # 2. Negative — execute before approval
    executor = ActuatorExecutor(db, connector=connector, allow_actuators=True, allowed_actuator_ids=[ACTUATOR_ID])
    w("## 2. Execute BEFORE approval → refused, no egress\n")
    try:
        executor.execute(pid)
    except ActuatorExecutionError as exc:
        w(f"- raised `ActuatorExecutionError`: {exc}")
    w(f"- `gh` calls: **{len(gh.calls)}** (unchanged)\n")

    # 3. Negative — a manifest-refused op never reaches the runner
    spy = FakeGh()
    refusing = build_gated_connector(
        GITHUB_ISSUE_MANIFEST,
        plan=lambda pr: GatedOperation.subprocess(["gh", "repo", "delete", "acme/app"]),
        interpret=lambda raw, op: {},
        runner=spy,
    )
    w("## 3. A non-allow-listed op (`gh repo delete`) → refused BEFORE egress\n")
    try:
        refusing(ActuatorProposal(target="github", action="create_issue", preview="x", payload={"repo": "acme/app"}))
    except ConnectorOperationRefused as exc:
        w(f"- raised `ConnectorOperationRefused`: {exc}")
    w(f"- runner calls: **{len(spy.calls)}** (the gate was never reached)\n")

    # 4. Approve + execute
    db.actuators.transition_proposal(pid, to_status="approved", actor="karol")
    executed = executor.execute(pid)
    w("## 4. Approve → execute → executed + result\n")
    w(f"- the one `gh` argv: `{gh.calls[-1]}`")
    w(f"- status: **{executed.status}**")
    w(f"- result: `{executed.result}`\n")

    # 5. Audit trail
    audit = db.actuators.list_audit(pid)
    w("## 5. The audit trail (every transition recorded)\n")
    w("| # | → status | actor | detail |")
    w("|---|---|---|---|")
    for i, a in enumerate(audit, 1):
        w(f"| {i} | {a.to_status} | {a.actor or '—'} | {(a.detail or '').replace('|', '/')} |")
    w("")
    w(f"**Lifecycle:** {' → '.join(a.to_status for a in audit)}")
    w(f"**Total real `gh` calls in this demo:** {len(gh.calls)} (exactly one — the executed issue).")

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
