"""HS-57-01 — the transcript parsers (VTT / SRT / TXT).

The honesty contract under test: real timestamps only when the file carries
them; speaker labels only from the file (voice tags / conservative `Name:`
prefixes); zero-cue input refused with an actionable error, never a silent
empty result; the module stays pure (no I/O / db / config imports).
"""
from __future__ import annotations

import pytest

from holdspeak.transcript_parse import (
    SYNTHETIC_CUE_SECONDS,
    TRANSCRIPT_SUFFIXES,
    ParsedTranscript,
    TranscriptParseError,
    parse_transcript,
)

# ── VTT ──────────────────────────────────────────────────────────────────────

# Teams/Zoom-shaped: BOM, CRLF, NOTE block, cue identifiers, voice tags
# (one without a closing tag), styling tags, an hour-less timing.
TEAMS_VTT = (
    "﻿WEBVTT\r\n"
    "\r\n"
    "NOTE\r\nGenerated by a meeting tool\r\n"
    "\r\n"
    "1\r\n"
    "00:00:01.000 --> 00:00:04.500\r\n"
    "<v Priya Sharma>Morning everyone, let's start.</v>\r\n"
    "\r\n"
    "2\r\n"
    "00:00:05.000 --> 00:00:09.000\r\n"
    "<v Sam Kowalski>I pushed the <c.highlight>fix</c> last night.\r\n"
    "\r\n"
    "3\r\n"
    "00:00:09.200 --> 00:00:12.000\r\n"
    "And the tests are green.\r\n"
    "\r\n"
    "01:30.000 --> 01:33.000\r\n"
    "<v Priya Sharma>Great, ship it.\r\n"
)


def test_vtt_real_world_shape() -> None:
    parsed = parse_transcript(TEAMS_VTT, "meeting.vtt")
    assert parsed.has_real_timestamps is True
    assert [c.speaker for c in parsed.cues] == [
        "Priya Sharma", "Sam Kowalski", "Sam Kowalski", "Priya Sharma"
    ]
    assert parsed.speakers_found == ["Priya Sharma", "Sam Kowalski"]
    assert parsed.cues[0].start == pytest.approx(1.0)
    assert parsed.cues[0].end == pytest.approx(4.5)
    # hour-less timing parses (MM:SS.mmm)
    assert parsed.cues[3].start == pytest.approx(90.0)
    # tags stripped, text joined
    assert parsed.cues[1].text == "I pushed the fix last night."
    # the bare cue continued the previous voice (per the VTT voice model)
    assert parsed.cues[2].text == "And the tests are green."


def test_vtt_multiline_cue_text_joins() -> None:
    vtt = (
        "WEBVTT\n\n"
        "00:00:00.000 --> 00:00:02.000\n"
        "line one\n"
        "line two\n"
    )
    parsed = parse_transcript(vtt, "x.vtt")
    assert parsed.cues[0].text == "line one line two"


def test_vtt_without_header_refused() -> None:
    with pytest.raises(TranscriptParseError, match="WEBVTT header"):
        parse_transcript("00:00:01.000 --> 00:00:02.000\nhi\n", "x.vtt")


def test_vtt_header_only_refused() -> None:
    with pytest.raises(TranscriptParseError, match="no readable cue blocks"):
        parse_transcript("WEBVTT\n\nNOTE nothing here\n", "x.vtt")


def test_vtt_unlabeled_cues_use_fallback_speaker() -> None:
    vtt = "WEBVTT\n\n00:00:00.000 --> 00:00:01.000\nhello there\n"
    parsed = parse_transcript(vtt, "x.vtt", fallback_speaker="Recording")
    assert parsed.cues[0].speaker == "Recording"
    assert parsed.speakers_found == []  # the file carried no labels


def test_vtt_content_with_txt_suffix_is_parsed_as_vtt() -> None:
    # Tools mislabel exports; the WEBVTT header wins over the suffix.
    parsed = parse_transcript(TEAMS_VTT, "meeting.txt")
    assert parsed.has_real_timestamps is True
    assert parsed.speakers_found == ["Priya Sharma", "Sam Kowalski"]


def test_vtt_end_not_after_start_clamped() -> None:
    vtt = "WEBVTT\n\n00:00:05.000 --> 00:00:05.000\noops\n"
    parsed = parse_transcript(vtt, "x.vtt")
    assert parsed.cues[0].end > parsed.cues[0].start


# ── SRT ──────────────────────────────────────────────────────────────────────

SRT = (
    "1\n"
    "00:00:01,000 --> 00:00:03,000\n"
    "Maria: Welcome back.\n"
    "\n"
    "2\n"
    "00:00:03,500 --> 00:00:06,000\n"
    "Thanks, glad to be here.\n"
    "\n"
    "3\n"
    "00:00:06,500 --> 00:00:08,000\n"
    "Jan Novak: One question from me.\n"
)


def test_srt_comma_times_and_name_prefixes() -> None:
    parsed = parse_transcript(SRT, "meeting.srt")
    assert parsed.has_real_timestamps is True
    assert parsed.cues[0].start == pytest.approx(1.0)
    assert parsed.cues[0].speaker == "Maria"
    assert parsed.cues[0].text == "Welcome back."
    # the unlabeled middle cue continues the previous speaker
    assert parsed.cues[1].speaker == "Maria"
    assert parsed.cues[2].speaker == "Jan Novak"
    assert parsed.speakers_found == ["Maria", "Jan Novak"]


def test_srt_garbage_refused() -> None:
    with pytest.raises(TranscriptParseError, match="SubRip"):
        parse_transcript("just some prose\nwith no timings\n", "x.srt")


# ── TXT ──────────────────────────────────────────────────────────────────────


def test_txt_labeled_and_continuation_lines() -> None:
    txt = (
        "Priya: We need the rollout note by Friday.\n"
        "and the changelog too.\n"
        "Sam: I'll draft both.\n"
    )
    parsed = parse_transcript(txt, "notes.txt")
    assert parsed.has_real_timestamps is False
    assert [c.speaker for c in parsed.cues] == ["Priya", "Priya", "Sam"]
    assert parsed.speakers_found == ["Priya", "Sam"]
    # synthetic, monotonic spacing
    starts = [c.start for c in parsed.cues]
    assert starts == sorted(starts)
    assert parsed.cues[1].start == pytest.approx(SYNTHETIC_CUE_SECONDS)


@pytest.mark.parametrize(
    "line",
    [
        "https://example.test/page is the doc",     # URL colon (no space)
        "12:30: lunch with the team",                # clock time (digits)
        "Note: remember to push the tag",            # structure label
        "Agenda: roadmap, hiring, demos",            # structure label
        "The plan is simple: ship it",               # colon mid-thought (4 words)
    ],
)
def test_txt_name_rule_rejects_non_names(line: str) -> None:
    parsed = parse_transcript(line + "\n", "notes.txt", fallback_speaker="Import")
    assert parsed.speakers_found == []
    assert parsed.cues[0].speaker == "Import"


def test_txt_unlabeled_uses_fallback() -> None:
    parsed = parse_transcript("hello\nworld\n", "n.txt", fallback_speaker="Memo")
    assert all(c.speaker == "Memo" for c in parsed.cues)
    assert parsed.speakers_found == []


# ── refusals + the module contract ───────────────────────────────────────────


def test_empty_input_refused() -> None:
    with pytest.raises(TranscriptParseError, match="empty or"):
        parse_transcript("", "x.txt")


def test_binary_garbage_refused() -> None:
    garbage = bytes(range(256)).decode("latin-1") * 8
    with pytest.raises(TranscriptParseError, match="does not look like a text"):
        parse_transcript(garbage, "x.txt")


def test_unsupported_suffix_refused() -> None:
    with pytest.raises(TranscriptParseError, match="Unsupported transcript format"):
        parse_transcript("hello\n", "x.docx")


def test_suffix_registry_is_the_v1_trio() -> None:
    assert TRANSCRIPT_SUFFIXES == frozenset({".vtt", ".srt", ".txt"})


def test_module_is_pure() -> None:
    import holdspeak.transcript_parse as mod

    source = open(mod.__file__).read()
    for forbidden in ("import sqlite3", "from .db", "from .config", "import requests",
                      "import httpx", "open("):
        assert forbidden not in source, f"pure parser module must not use {forbidden!r}"


def test_parsed_transcript_shape() -> None:
    parsed = parse_transcript("Ana: hi\n", "x.txt")
    assert isinstance(parsed, ParsedTranscript)
    cue = parsed.cues[0]
    assert (cue.text, cue.speaker) == ("hi", "Ana")
